/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuizResult = IDL.Record({
  'score' : IDL.Nat,
  'quizId' : IDL.Text,
  'passed' : IDL.Bool,
});
export const UserProgress = IDL.Record({
  'completedModules' : IDL.Vec(IDL.Text),
  'completedSimulations' : IDL.Vec(IDL.Text),
  'completedDomains' : IDL.Vec(IDL.Text),
  'readLessons' : IDL.Vec(IDL.Text),
  'quizResults' : IDL.Vec(QuizResult),
});
export const StreakStats = IDL.Record({
  'today' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const TimeStats = IDL.Record({
  'domain' : IDL.Text,
  'seconds' : IDL.Nat,
});
export const TimeBreakdown = IDL.Record({
  'totalTime' : IDL.Nat,
  'perDomain' : IDL.Vec(TimeStats),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletionStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'modulesCompleted' : IDL.Nat,
          'domainsCompleted' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMyProgress' : IDL.Func([], [UserProgress], ['query']),
  'getMyStreakStats' : IDL.Func([], [StreakStats], ['query']),
  'getTimeBreakdown' : IDL.Func([], [TimeBreakdown], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markDomainComplete' : IDL.Func([IDL.Text], [], []),
  'markLessonRead' : IDL.Func([IDL.Text], [], []),
  'markModuleComplete' : IDL.Func([IDL.Text], [], []),
  'markSimulationDone' : IDL.Func([IDL.Text], [], []),
  'recordTimeSpent' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuiz' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'updateStreakStats' : IDL.Func([IDL.Nat], [StreakStats], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuizResult = IDL.Record({
    'score' : IDL.Nat,
    'quizId' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const UserProgress = IDL.Record({
    'completedModules' : IDL.Vec(IDL.Text),
    'completedSimulations' : IDL.Vec(IDL.Text),
    'completedDomains' : IDL.Vec(IDL.Text),
    'readLessons' : IDL.Vec(IDL.Text),
    'quizResults' : IDL.Vec(QuizResult),
  });
  const StreakStats = IDL.Record({
    'today' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const TimeStats = IDL.Record({ 'domain' : IDL.Text, 'seconds' : IDL.Nat });
  const TimeBreakdown = IDL.Record({
    'totalTime' : IDL.Nat,
    'perDomain' : IDL.Vec(TimeStats),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletionStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'modulesCompleted' : IDL.Nat,
            'domainsCompleted' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyProgress' : IDL.Func([], [UserProgress], ['query']),
    'getMyStreakStats' : IDL.Func([], [StreakStats], ['query']),
    'getTimeBreakdown' : IDL.Func([], [TimeBreakdown], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markDomainComplete' : IDL.Func([IDL.Text], [], []),
    'markLessonRead' : IDL.Func([IDL.Text], [], []),
    'markModuleComplete' : IDL.Func([IDL.Text], [], []),
    'markSimulationDone' : IDL.Func([IDL.Text], [], []),
    'recordTimeSpent' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuiz' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'updateStreakStats' : IDL.Func([IDL.Nat], [StreakStats], []),
  });
};

export const init = ({ IDL }) => { return []; };