/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuizResult {
  'score' : bigint,
  'quizId' : string,
  'passed' : boolean,
}
export interface StreakStats {
  'today' : bigint,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface TimeBreakdown {
  'totalTime' : bigint,
  'perDomain' : Array<TimeStats>,
}
export interface TimeStats { 'domain' : string, 'seconds' : bigint }
export interface UserProfile { 'name' : string }
export interface UserProgress {
  'completedModules' : Array<string>,
  'completedSimulations' : Array<string>,
  'completedDomains' : Array<string>,
  'readLessons' : Array<string>,
  'quizResults' : Array<QuizResult>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletionStats' : ActorMethod<
    [],
    { 'modulesCompleted' : bigint, 'domainsCompleted' : bigint }
  >,
  'getMyProgress' : ActorMethod<[], UserProgress>,
  'getMyStreakStats' : ActorMethod<[], StreakStats>,
  'getTimeBreakdown' : ActorMethod<[], TimeBreakdown>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDomainComplete' : ActorMethod<[string], undefined>,
  'markLessonRead' : ActorMethod<[string], undefined>,
  'markModuleComplete' : ActorMethod<[string], undefined>,
  'markSimulationDone' : ActorMethod<[string], undefined>,
  'recordTimeSpent' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuiz' : ActorMethod<[string, bigint, boolean], undefined>,
  'updateStreakStats' : ActorMethod<[bigint], StreakStats>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];